# Generated by Django 2.2.7 on 2019-12-04 04:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='title', max_length=50, unique=True)),
                ('category', models.CharField(default='Not Available', max_length=20)),
                ('cast', models.TextField(default='cast')),
                ('director', models.CharField(default='None', max_length=25)),
                ('producer', models.CharField(default='None', max_length=25)),
                ('rating', models.CharField(default='NR', max_length=5)),
                ('poster', models.CharField(max_length=255)),
                ('currentlyPlaying', models.BooleanField(default=False)),
                ('synopsis', models.TextField(default='synopsis')),
                ('trailer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.FloatField(default=0.5)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='seatInShowTime',
            fields=[
                ('seatNumber', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('seatOccupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_rows', models.IntegerField()),
                ('seat_columns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.IntegerField(primary_key=True, serialize=False)),
                ('ageType', models.CharField(choices=[('Child', 'Child'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showroom_name', models.IntegerField(default=0)),
                ('movie_name', models.CharField(default='None', max_length=25)),
                ('scheduledTime', models.TimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Movie')),
                ('seatInShowTime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seatInShowTime')),
                ('showroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Showroom')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Ticket')),
            ],
            options={
                'unique_together': {('showroom_id', 'scheduledTime')},
            },
        ),
        migrations.AddField(
            model_name='seatinshowtime',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Show'),
        ),
    ]
