# Generated by Django 2.2.7 on 2019-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(default='cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Not Available', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='currentlyPlaying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default.jpg', upload_to='movie_posters'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='NR', max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(default='synopsis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
