# Generated by Django 2.2.7 on 2019-12-04 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatinshowtime',
            name='seatOccupied',
        ),
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seatInShowTime_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='promo', max_length=24),
        ),
        migrations.AddField(
            model_name='seatinshowtime',
            name='seatStatus',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Filled', 'Filled'), ('Pending', 'Pending')], default='Empty', max_length=10),
        ),
        migrations.AddField(
            model_name='show',
            name='show_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='seat_columns',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='seat_rows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
