# Generated by Django 2.2.7 on 2019-11-21 04:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20191118_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promoID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('showroom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('numSeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scheduledTime', models.TimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Movie')),
                ('showroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Showroom')),
            ],
        ),
        migrations.CreateModel(
            name='seatInShowTime',
            fields=[
                ('seatNumber', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('seatOccupied', models.BooleanField(default=False)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Show')),
            ],
        ),
    ]
