# Generated by Django 2.2.7 on 2019-11-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_promotion_seatinshowtime_show_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='title', max_length=50, unique=True),
        ),
    ]
