# Generated by Django 2.2.7 on 2019-11-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_show_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='numSeats',
            field=models.IntegerField(),
        ),
    ]
