# Generated by Django 2.2.7 on 2019-12-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20191204_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='seatInShowTime',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinema.seatInShowTime'),
        ),
    ]
