# Generated by Django 2.2.7 on 2019-11-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20191121_0438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('showroom_id', 'scheduledTime')},
        ),
    ]
