# Generated by Django 2.2.7 on 2019-11-21 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20191120_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='showroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Showroom'),
        ),
        migrations.CreateModel(
            name='seatInShowTime',
            fields=[
                ('seatNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Show')),
            ],
        ),
    ]
