# Generated by Django 2.2.7 on 2019-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20191121_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='movie_name',
            field=models.CharField(default='None', max_length=25),
        ),
        migrations.AddField(
            model_name='show',
            name='showroom_name',
            field=models.IntegerField(default=0),
        ),
    ]
