# Generated by Django 2.2.7 on 2019-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20191204_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatinshowtime',
            name='show_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='seatInShowTime',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ticket',
        ),
    ]
