# Generated by Django 2.2.7 on 2019-11-21 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20191120_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatinshowtime',
            old_name='status',
            new_name='seatOccupied',
        ),
        migrations.AlterField(
            model_name='seatinshowtime',
            name='seatNumber',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
