# Generated by Django 2.2.7 on 2019-12-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20191204_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatinshowtime',
            name='show_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.Show'),
        ),
    ]
