# Generated by Django 2.2.7 on 2019-11-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20191121_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
