# Generated by Django 2.2.7 on 2019-11-21 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20191120_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatinshowtime',
            name='seatNumber',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
