# Generated by Django 2.2.7 on 2019-12-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_seatinshowtime_show_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatinshowtime',
            name='seatNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
