# Generated by Django 2.2.7 on 2019-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20191120_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promoID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
