# Generated by Django 2.2.7 on 2019-12-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20191204_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='seatInShowTime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cinema.seatInShowTime'),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cinema.Ticket'),
        ),
    ]
