# Generated by Django 2.2.7 on 2019-11-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
