# Generated by Django 2.2.7 on 2019-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=6),
        ),
    ]
