# Generated by Django 2.2.7 on 2019-12-04 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('promo_register', models.BooleanField(default=False)),
                ('billing_address', models.CharField(default='123 North Street', max_length=50)),
                ('card_number', models.CharField(default='1234123412341234', max_length=16)),
                ('exp_date', models.CharField(default='01/99', max_length=5)),
                ('card_type', models.CharField(default='MC', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
