# Generated by Django 2.2.7 on 2019-12-04 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_type',
            field=models.CharField(default='MC', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp_date',
            field=models.DateField(default=datetime.date(2019, 12, 4)),
        ),
    ]
