# Generated by Django 2.2.7 on 2019-12-04 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191204_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exp_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
