# Generated by Django 2.2.7 on 2019-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191111_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.CharField(default='123 North Street', max_length=50),
        ),
    ]
