# Generated by Django 2.2.7 on 2019-12-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191204_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exp_date',
            field=models.CharField(default='01/99', max_length=5),
        ),
    ]
