# Generated by Django 2.2.7 on 2019-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191111_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='promo_register',
            field=models.BooleanField(default=False),
        ),
    ]
