# Generated by Django 2.2.7 on 2019-11-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_promo_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default='1234123412341234', max_length=16),
        ),
    ]
